2020-11-25 04:33:34,721: DEBUG: NEW RUN: Client, TEST: Write_Multiple_Clients_Five_Threads0
2020-11-25 04:33:34,721: DEBUG: The client is starting.
2020-11-25 04:33:34,721: DEBUG: The client is starting on port 22183
2020-11-25 04:33:34,721: DEBUG: Sent WRQ: b'\x00\x02/home/A365/tftp_threads/dist/read_files/thread_0.txt\x00netascii\x00'
2020-11-25 04:33:34,723: DEBUG: File exists, can send it
2020-11-25 04:33:34,723: DEBUG: First packet received. Raw bytes: b'\x00\x05\x00\x02filename already exists at destination\x00'
2020-11-25 04:33:34,724: DEBUG: New packet from: ('127.0.0.1', 39001), contents: b'\x00\x05\x00\x02filename already exists at destination\x00'
2020-11-25 04:33:34,724: DEBUG: Sending: /home/A365/tftp_threads/dist/read_files/thread_0.txt
2020-11-25 04:33:34,724: ERROR: Shutting down due to error packet. Error code: 2, error message: b'filename already exists at destination'
2020-11-25 04:33:34,724: WARNING: File didnt close on its own, closing now
2020-11-25 04:33:34,824: DEBUG: Client finished.
2020-11-25 04:33:34,824: DEBUG: Closing Socket
