2020-11-25 04:33:38,495: DEBUG: NEW RUN: Client, TEST: Write_Multiple_Clients_Ten_Threads3
2020-11-25 04:33:38,495: DEBUG: The client is starting.
2020-11-25 04:33:38,495: DEBUG: The client is starting on port 12702
2020-11-25 04:33:38,496: DEBUG: Sent WRQ: b'\x00\x02/home/A365/tftp_threads/dist/read_files/thread_3.txt\x00netascii\x00'
2020-11-25 04:33:38,498: DEBUG: First packet received. Raw bytes: b'\x00\x05\x00\x02filename already exists at destination\x00'
2020-11-25 04:33:38,498: DEBUG: File exists, can send it
2020-11-25 04:33:38,498: DEBUG: New packet from: ('127.0.0.1', 26756), contents: b'\x00\x05\x00\x02filename already exists at destination\x00'
2020-11-25 04:33:38,499: DEBUG: Sending: /home/A365/tftp_threads/dist/read_files/thread_3.txt
2020-11-25 04:33:38,499: ERROR: Shutting down due to error packet. Error code: 2, error message: b'filename already exists at destination'
2020-11-25 04:33:38,499: WARNING: File didnt close on its own, closing now
2020-11-25 04:33:38,599: DEBUG: Client finished.
2020-11-25 04:33:38,599: DEBUG: Closing Socket
